services:
  frontend:
    container_name: vexgen_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '3000:3000'
    networks:
      - depex

  backend:
    container_name: vexgen_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
      - .env:/backend/.env
    depends_on:
      pypi_graph_database:
        condition: service_healthy
      npm_graph_database:
        condition: service_healthy
      maven_graph_database:
        condition: service_healthy
      cargo_graph_database:
        condition: service_healthy
      nuget_graph_database:
        condition: service_healthy
      vuln_database:
        condition: service_started
    ports:
      - '8000:8000'
    networks:
      - vexgen
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  pypi_graph_database:
    env_file: .env
    container_name: pypi_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_PYPI}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7474
      - NEO4J_server_http_advertised__address=:7474
      - NEO4J_server_bolt_listen__address=:7687
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./seeds/graphs/pypi_neo4j.cypher.gz:/backups/pypi_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s

  npm_graph_database:
    env_file: .env
    container_name: npm_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_NPM}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7473
      - NEO4J_server_http_advertised__address=:7473
      - NEO4J_server_bolt_listen__address=:7686
      - NEO4J_server_bolt_advertised__address=:7686
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7473:7473'
      - '7686:7686'
    volumes:
      - ./seeds/graphs/npm_neo4j.cypher.gz:/backups/npm_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7473 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s

  maven_graph_database:
    env_file: .env
    container_name: maven_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_MAVEN}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7472
      - NEO4J_server_http_advertised__address=:7472
      - NEO4J_server_bolt_listen__address=:7685
      - NEO4J_server_bolt_advertised__address=:7685
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7472:7472'
      - '7685:7685'
    volumes:
      - ./seeds/graphs/maven_neo4j.cypher.gz:/backups/maven_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7472 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s

  cargo_graph_database:
    env_file: .env
    container_name: cargo_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_CARGO}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7471
      - NEO4J_server_http_advertised__address=:7471
      - NEO4J_server_bolt_listen__address=:7684
      - NEO4J_server_bolt_advertised__address=:7684
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7471:7471'
      - '7684:7684'
    volumes:
      - ./seeds/graphs/cargo_neo4j.cypher.gz:/backups/cargo_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7471 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s

  nuget_graph_database:
    env_file: .env
    container_name: nuget_neo4j
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER}/${GRAPH_DB_PASSWORD_NUGET}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_listen__address=:7470
      - NEO4J_server_http_advertised__address=:7470
      - NEO4J_server_bolt_listen__address=:7683
      - NEO4J_server_bolt_advertised__address=:7683
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - '7470:7470'
      - '7683:7683'
    volumes:
      - ./seeds/graphs/nuget_neo4j.cypher.gz:/backups/nuget_neo4j.cypher.gz
    networks:
      - vexgen
    healthcheck:
      test: wget http://localhost:7470 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s

  vuln_database:
    env_file: .env
    container_name: mongodb
    image: mongo:7.0.11
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${VULN_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${VULN_DB_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - vexgen

networks:
  vexgen:
    driver: bridge
